@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Jan 02 16:38:46 +0100 2026
REM SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim Temporizador_tb_behav -key {Behavioral:sim_1:Functional:Temporizador_tb} -tclbatch Temporizador_tb.tcl -view C:/Trabajo_SED/Mux_tb_behav.wcfg -view C:/Trabajo_SED/Debouncer_tb_behav.wcfg -view C:/Trabajo_SED/Cafetera_tb_behav.wcfg -view C:/Trabajo_SED/Clk_Divisor_tb_behav.wcfg -view C:/Trabajo_SED/DetectFlanco_tb_behav.wcfg -view C:/Trabajo_SED/Sincronizador_tb_behav.wcfg -view C:/Trabajo_SED/Zumbador_tb_behav.wcfg -log simulate.log"
call xsim  Temporizador_tb_behav -key {Behavioral:sim_1:Functional:Temporizador_tb} -tclbatch Temporizador_tb.tcl -view C:/Trabajo_SED/Mux_tb_behav.wcfg -view C:/Trabajo_SED/Debouncer_tb_behav.wcfg -view C:/Trabajo_SED/Cafetera_tb_behav.wcfg -view C:/Trabajo_SED/Clk_Divisor_tb_behav.wcfg -view C:/Trabajo_SED/DetectFlanco_tb_behav.wcfg -view C:/Trabajo_SED/Sincronizador_tb_behav.wcfg -view C:/Trabajo_SED/Zumbador_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
